dependencies:
  # <organization/repo>@version
  # - smartcontractkit/chainlink@1.8.0
  - smartcontractkit/chainlink@2.9.1
  - OpenZeppelin/openzeppelin-contracts@4.9.2

compiler:
  solc:
    version: "0.8.1"
    remappings:
      # - "@chainlink=smartcontractkit/chainlink@1.8.0"
      - "@chainlink=smartcontractkit/chainlink@2.9.1"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.9.2"

networks:
  development:
    verify: False
  local-ganache:
    verify: False
  sepolia:
    host: https://sepolia.infura.io/v3/235b941d748d4862afcd01152d6d4152
    gas_limit: auto
    gas_price: auto
    chainid: 11155111
    explorer: https://api-sepolia.etherscan.io/api
    verify: True
  eth_usd_price_feed: '0x694AA1769357215DE4FAC081bf1f309aDC325306'
  mainnet:
    verify: True
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'

networks:
  mainnet-infura:
    host: https://sepolia.infura.io/v3/235b941d748d4862afcd01152d6d4152
    chainid: 11155111
    gas_price: auto
    timeout: 60

dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
